Done

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -24,14 +24,14 @@ DISK=/dev/sda                            # SET DISK FOR INSTALLATION
 
 # SET PARTITION SIZE :
 # ~~~~~~~~~~~~~~~~~~~~
-BOOTSIZE=500                             # SET BOOT PARTITION SIZE ( NOTE - SIZE IS IN MB )
-ROOTSIZE=50                              # SET ROOT PARTITION SIZE ( NOTE - SIZE IS IN GB )
+BOOTSIZE=500                             # SET BOOT PARTITION SIZE ( SIZE MUST BE IN MB )
+ROOTSIZE=50                              # SET ROOT PARTITION SIZE ( SIZE MUST BE IN GB )
 HOMESIZE=                                # REMAINING SPACE FOR HOME PARTITION
 
 # SET SWAP SIZE :
 # ~~~~~~~~~~~~~~~
 SWAP=2                                   # 0 = NO SWAP , 1 = SWAP PARTITION & 2 = SWAP FILE 
-SWAPSIZE=8                               # SET SIZE OF SWAP PARTITION OR SWAP FILE ( NOTE - SIZE IS IN GB )
+SWAPSIZE=4                               # SET SIZE OF SWAP PARTITION OR SWAP FILE ( SIZE MUST BE IN MB )
 
 # SET BOOT LOADER :
 # ~~~~~~~~~~~~~~~~~
@@ -40,7 +40,7 @@ BOOTLOADER=1                             # 0 = GRUB & 1 = SYSTEMD-BOOT
 # SET PACKAGES :
 # ~~~~~~~~~~~~~~
 KERNEL="linux-lts"                       # SET KERNEL PACKAGES
-EDITOR="neovim"                          # SET EDITOR
+EDITOR="neovim"                          # SET EDITOR PACKAGES
 PACKAGES="git"                           # INSTALL EXTRA PACKAGES 
 
 # SET LOG FILE :
@@ -61,12 +61,19 @@ BP="\e[1;35m"
 BC="\e[1;36m"
 NO="\e[0m"
 
-# PRETTY PRINT FUNCTIONS :
+# PRINT FUNCTIONS :
 # ~~~~~~~~~~~~~~~~~~~~~~~~
 _Info_Print () {
     echo 
     echo -ne "\r${BG}     ! NOTE !${BB} - $1${NO}\n"
     read -n 1 -s -r _
+}
+
+_Error_Print () {
+    echo 
+    echo -ne "\r${BG}     ! ERROR !${BB} - $1${NO}\n"
+    read -n 1 -s -r _
+    exit 1
 }
 
 _Chrooting_Print () {
@@ -93,26 +100,6 @@ _Chrooting_Print () {
         echo -ne "\r${BG}     ! ERROR !${BR} - INVALID INPUT.${NO}\n"
         _Chrooting_Print
     fi
-}
-
-_Error_Print () {
-    echo 
-    echo -ne "\r${BG}     ! ERROR !${BB} - $1${NO}\n"
-    read -n 1 -s -r _
-    exit 1
-}
-
-# TITLE PRINT FUNCTION :
-# ~~~~~~~~~~~~~~~~~~~~~~
-_Title_Print () {
-    COLUMNS=$(tput cols)
-    SIZE=$1
-    INDENT=$(( (COLUMNS - SIZE) / 2 ))
-    PADDING=''
-    for ((i=1; i<=INDENT; i++)) ; do
-        PADDING+=' '
-    done
-    echo -e "${BP}${PADDING}${2}${NO}"
 }
 
 # ---------------------------------------------------------- #
@@ -162,69 +149,69 @@ _Install_Outline_Steps () {
     _Install_Title
 
     if [ "${_Checking_Requirements_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.0  Checking Requirements${BG}              - [ Complete ]${NO}\n"                     
+        echo -ne "\r${BC}     1.0  Checking Requirements${BG}              - [ Complete ]${NO}\n\n"                     
     else
-        echo -ne "\r${BY}     1.0  Checking Requirements${BR}              - [ Incomplete ]${NO}\n"                     
+        echo -ne "\r${BY}     1.0  Checking Requirements${BR}              - [ Incomplete ]${NO}\n\n"                     
     fi
 
     if [ "${_Checking_Var_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.1  Checking The Variable${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.1  Checking The Variable${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.1  Checking The Variable${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.1  Checking The Variable${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Setting_DTime_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.2  Setting Date And Time${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.2  Setting Date And Time${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.2  Setting Date And Time${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.2  Setting Date And Time${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Setting_Pacman_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.3  Setting Pacman Config${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.3  Setting Pacman Config${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.3  Setting Pacman Config${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.3  Setting Pacman Config${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Checking_Dep_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.4  Checking Dependencies${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.4  Checking Dependencies${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.4  Checking Dependencies${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.4  Checking Dependencies${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Wiping_Disks_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.5  Wiping Selected Disks${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.5  Wiping Selected Disks${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.5  Wiping Selected Disks${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.5  Wiping Selected Disks${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Creating_Partition_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.6  Creating A Partitions${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.6  Creating A Partitions${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.6  Creating A Partitions${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.6  Creating A Partitions${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Formatting_Partition_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.7  Formatting Partitions${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.7  Formatting Partitions${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.7  Formatting Partitions${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.7  Formatting Partitions${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Mounting_Partition_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.8  Mounting A Partitions${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.8  Mounting A Partitions${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.8  Mounting A Partitions${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.8  Mounting A Partitions${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Installing_Arch_Complete}" = true ]; then
-        echo -ne "\r${BC}     1.9  Installing Arch Linux${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     1.9  Installing Arch Linux${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     1.9  Installing Arch Linux${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     1.9  Installing Arch Linux${BR}              - [ Incomplete ]${NO}\n\n"
     fi
      
     if [ "${_Generating_FSTab_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.0  Generating FSTab File${BG}              - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.0  Generating FSTab File${BG}              - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.0  Generating FSTab File${BR}              - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.0  Generating FSTab File${BR}              - [ Incomplete ]${NO}\n\n"
     fi
 }
 
@@ -233,63 +220,63 @@ _Chroot_Outline_Steps () {
     _Chroot_Title
     
     if [ "${_Setting_Localization_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.1  Setting Localizations${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.1  Setting Localizations${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.1  Setting Localizations${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.1  Setting Localizations${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Configuring_NManager_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.2  Configuring A Network${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.2  Configuring A Network${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.2  Configuring A Network${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.2  Configuring A Network${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Setting_PacManager_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.3  Setting Pacman Config${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.3  Setting Pacman Config${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.3  Setting Pacman Config${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.3  Setting Pacman Config${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Optimizing_Experience_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.4  Optimizing Experience${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.4  Optimizing Experience${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.4  Optimizing Experience${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.4  Optimizing Experience${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Setting_BLoader_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.5  Setting A Boot Loader${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.5  Setting A Boot Loader${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.5  Setting A Boot Loader${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.5  Setting A Boot Loader${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Installing_Packages_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.6  Installing A Packages${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.6  Installing A Packages${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.6  Installing A Packages${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.6  Installing A Packages${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Creating_SFile_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.7  Creating A Swap Files${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.7  Creating A Swap Files${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.7  Creating A Swap Files${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.7  Creating A Swap Files${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Setting_RPass_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.8  Setting Root Password${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.8  Setting Root Password${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.8  Setting Root Password${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.8  Setting Root Password${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Setting_User_Complete}" = true ]; then
-        echo -ne "\r${BC}     2.9  Setting  User Account${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     2.9  Setting  User Account${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     2.9  Setting  User Account${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     2.9  Setting  User Account${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 
     if [ "${_Coping_Logs_Complete}" = true ]; then
-        echo -ne "\r${BC}     3.0  Coping The Logs Files${BG}               - [ Complete ]${NO}\n"
+        echo -ne "\r${BC}     3.0  Coping The Logs Files${BG}               - [ Complete ]${NO}\n\n"
     else
-        echo -ne "\r${BY}     3.0  Coping The Logs Files${BR}               - [ Incomplete ]${NO}\n"
+        echo -ne "\r${BY}     3.0  Coping The Logs Files${BR}               - [ Incomplete ]${NO}\n\n"
     fi
 }
 
@@ -305,10 +292,9 @@ printf '\e[?25l\e[?7l'
 # TITLE SHOW :
 # ~~~~~~~~~~~~
 _Install_Title () {
-    echo
-    _Title_Print 17 "╔═══════════════╗"
-    _Title_Print 17 "║  ARCH INSTALL ║"
-    _Title_Print 17 "╚═══════════════╝"
+    echo -e "${BG}"
+    figlet -tc "arch install"
+    echo -e "${NO}"
     echo
 }
 
@@ -565,10 +551,9 @@ _Installing_Complete () {
 # ---------------------------------------------------------- #
 
 _Chroot_Title () {
-    echo
-    _Title_Print 17 "╔═══════════════╗"
-    _Title_Print 17 "║  ARCH CHROOT  ║"
-    _Title_Print 17 "╚═══════════════╝"
+    echo -e "${BG}"
+    figlet -tc "arch chroot"
+    echo -e "${NO}"
     echo
 }
 
@@ -818,6 +803,12 @@ _Chrooting () {
     _Chrooting_Complete
 }
 
-_Installing
+# _Installing
 
-_Chrooting
+# _Chrooting
+
+clear
+_Install_Outline_Steps
+sleep 5
+clear
+_Chroot_Outline_Steps
